
[[_gettreeusingget_1]]
==== 单模型构件分类树
....
GET /v2/files/{fileId}/tree
POST /v2/files/{fileId}/tree
....


===== 说明
单模型构件分类树, treeType接受两个值：default和customized,默认为default. v参数用来区别treeType为default时返回树的格式, customized总是返回格式2.0的构件树. 当treeType为"customized"时
- desiredHierarchy表示了筛选树的层次,可选值有building,systemType,specialty,floor,category,family,familyType，如:desiredHierarchy=specialty,systemtype
- customizedNodeKeys: 用来指定筛选树每个维度用id或者是name作为唯一标识, 如"floor":"id"


===== 参数

[options="header", cols=".^2a,.^3a,.^9a,.^4a,.^2a"]
|===
|类型|名称|说明|类型|默认值
|**Header**|**Authorization** +
__必填__|authorization header|string|`"bearer "`
|**Path**|**fileId** +
__必填__|fileId|integer (int64)|
|**Query**|**treeType** +
__可选__|treeType|string|`"default"`
|**Query**|**v** +
__可选__|v|string|
|**Body**|**fileTreeRequest** +
__可选__|fileTreeRequest|<<_filetreerequestbody,FileTreeRequestBody>>|
|===


===== 响应

[options="header", cols=".^2a,.^14a,.^4a"]
|===
|HTTP代码|说明|类型
|**200**|OK|<<_b80c1d2d7c7ac73beacfcf91f5090656,GeneralResponse«object»>>
|**401**|Unauthorized|无内容
|**403**|Forbidden|无内容
|**404**|Not Found|无内容
|===
===== 生成

* `application/json`
* `\*/*`


===== HTTP请求示例

====== 请求 path
----
/v2/files/0/tree
----


====== 请求 header
[source,json]
----
"string"
----


====== 请求 body
[source,json]
----
{
  "customizedNodeKeys" : {
    "string" : "string"
  },
  "desiredHierarchy" : [ "string" ]
}
----


===== HTTP响应示例

====== 响应 200
[source,json]
----
{
  "code" : "success",
  "message" : null,
   {
      "categoryId": "-2000011",
      "categoryName": "墙",
      "families": [
      {
          "family": "基本墙",
          "familyTypes": [
              "125mm厚轻钢龙骨墙",
              "125mm防火墙",
              "150mm防火墙",
           ]
       },
      {
        "family": "墙 10",
        "familyTypes": [
            "墙 1"
        ]
       }
      ]
   }
}
----
include::detail/fail.adoc[]
include::detail/error.adoc[]


